/*
 * generated by Xtext
 */
package org.fornax.cartridges.sculptor.gui.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SculptorguidslUiModule extends org.fornax.cartridges.sculptor.gui.dsl.ui.AbstractSculptorguidslUiModule {

	public SculptorguidslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		// TODO Auto-generated constructor stub
	}

}
