/*
 * generated by Xtext
 */
package org.fornax.cartridges.sculptor.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SculptordslUiModule extends org.fornax.cartridges.sculptor.dsl.ui.AbstractSculptordslUiModule {

    public SculptordslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
        return SculptordslSemanticHighlightingCalculator.class;
    }

}
