/*
 * generated by Xtext
 */
package org.fornax.cartridges.sculptor.gui.dsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslAddTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslCreateTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslDeleteTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslGuiListSubtask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslGuiListSubtaskForTarget;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslGuiModule;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslGuiPreviewProperty;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslGuiViewProperty;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslImport;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslListTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslSkipAddTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslSkipCreateTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslSkipDeleteTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslSkipDomainObject;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslSkipListTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslSkipUpdateTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslUpdateTask;
import org.fornax.cartridges.sculptor.gui.dsl.sculptorguidsl.DslViewTask;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SculptorguidslLabelProvider extends DefaultEObjectLabelProvider {

    public String text(DslImport imp) {
        String uri = imp.getImportURI();
        int i = uri.lastIndexOf('/');
        String name;
        if (i != -1) {
            name = uri.substring(i + 1);
        } else {
            name = uri;
        }
        return "import " + name;
    }

    public String image(DslImport obj) {
        return "import.gif";
    }

    String text(DslGuiModule elem) {
        return (elem.getFor() != null) ? elem.getFor().getName() : null;
    }

    String text(DslDeleteTask elem) {
        return (elem.getFor() != null) ? "delete " + elem.getFor().getName() : null;
    }

    String text(DslCreateTask elem) {
        return (elem.getFor() != null) ? "create " + elem.getFor().getName() : null;
    }

    String text(DslUpdateTask elem) {
        return (elem.getFor() != null) ? "update " + elem.getFor().getName() : null;
    }

    String text(DslViewTask elem) {
        return (elem.getFor() != null) ? "view " + elem.getFor().getName() : null;
    }

    String text(DslListTask elem) {
        return (elem.getFor() != null) ? "list " + elem.getFor().getName() : null;
    }

    String text(DslAddTask elem) {
        return (elem.getFor() != null) ? "add " + elem.getFor().getName() : null;
    }

    String text(DslGuiViewProperty elem) {
        if (elem.getFor() == null) {
            return null;
        } else if (elem.getBasicTypeProperty() == null) {
            return elem.getFor().getName();
        } else {
            return elem.getFor().getName() + "." + elem.getBasicTypeProperty().getName();
        }
    }

    String text(DslGuiPreviewProperty elem) {
        if (elem.getFor() == null) {
            return null;
        } else if (elem.getBasicTypeProperty() == null) {
            return elem.getFor().getName();
        } else {
            return elem.getFor().getName() + "." + elem.getBasicTypeProperty().getName();
        }
    }

    String text(DslGuiListSubtask elem) {
        return (elem.getReference() != null) ? "list " + elem.getReference().getName() : null;
    }

    String text(DslGuiListSubtaskForTarget elem) {
        return (elem.getTarget() != null) ? "for target " + elem.getTarget().getName() : null;
    }

    String text(DslSkipAddTask elem) {
        return (elem.getFor() != null) ? "skip add " + elem.getFor().getName() : null;
    }

    String text(DslSkipCreateTask elem) {
        return (elem.getFor() != null) ? "skip create " + elem.getFor().getName() : null;
    }

    String text(DslSkipUpdateTask elem) {
        return (elem.getFor() != null) ? "skip update " + elem.getFor().getName() : null;
    }

    String text(DslSkipListTask elem) {
        return (elem.getFor() != null) ? "skip list " + elem.getFor().getName() : null;
    }

    String text(DslSkipDeleteTask elem) {
        return (elem.getFor() != null) ? "skip delete " + elem.getFor().getName() : null;
    }

    String text(DslSkipDomainObject elem) {
        return (elem.getDo() != null) ? "skip  " + elem.getDo().getName() : null;
    }

    @Override
    public String image(Object obj) {
        return "default.gif";
    }

    String image(DslGuiModule elem) {
        return "module.gif";
    }

    String image(DslCreateTask elem) {
        return "create2.gif";
    }

    String image(DslDeleteTask elem) {
        return "delete2.gif";
    }

    String image(DslUpdateTask elem) {
        return "update2.gif";
    }

    String image(DslViewTask elem) {
        return "view2.gif";
    }

    String image(DslListTask elem) {
        return "list2.gif";
    }

    String image(DslAddTask elem) {
        return "add2.gif";
    }

    String image(DslGuiViewProperty elem) {
        return "property3.gif";
    }

    String image(DslGuiPreviewProperty elem) {
        return "property3.gif";
    }

    String image(DslGuiListSubtask elem) {
        return "reference2.gif";
    }

    String image(DslSkipAddTask elem) {
        return "skiptask.gif";
    }

    String image(DslSkipCreateTask elem) {
        return "skiptask.gif";
    }

    String image(DslSkipUpdateTask elem) {
        return "skiptask.gif";
    }

    String image(DslSkipListTask elem) {
        return "skiptask.gif";
    }

    String image(DslSkipDeleteTask elem) {
        return "skiptask.gif";
    }

    String image(DslSkipDomainObject elem) {
        return "skipdo.gif";
    }

}
