/*
 * generated by Xtext
 */
package org.fornax.cartridges.sculptor.gui.dsl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SculptorguidslRuntimeModule extends org.fornax.cartridges.sculptor.gui.dsl.AbstractSculptorguidslRuntimeModule {

}
