/*
 * generated by Xtext
 */
package org.fornax.cartridges.sculptor.dsl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SculptordslRuntimeModule extends org.fornax.cartridges.sculptor.dsl.AbstractSculptordslRuntimeModule {

    // contributed by org.eclipse.xtext.generator.validation.CheckFragment
    @Override
    @org.eclipse.xtext.service.SingletonBinding(eager=true) public Class<? extends org.fornax.cartridges.sculptor.dsl.validation.SculptordslCheckValidator> bindSculptordslCheckValidator() {
        return org.fornax.cartridges.sculptor.dsl.validation.SculptordslCheckValidator2.class;
    }

}
