/*
* generated by Xtext
*/
package org.fornax.cartridges.sculptor.gui.dsl.ui.contentassist;

import org.fornax.cartridges.sculptor.gui.dsl.ui.contentassist.AbstractSculptorguidslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SculptorguidslProposalProvider extends AbstractSculptorguidslProposalProvider {

}
