/*
* generated by Xtext
*/
package org.fornax.cartridges.sculptor.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class SculptordslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
