/*
* generated by Xtext
*/
package org.sculptor.gui.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SculptorguidslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
